name: CI

on:
   pull_request:
      branches: ['*']
   push:
      branches: ['master']

jobs:
   check-and-build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Use Node.js version from .nvmrc
           uses: actions/setup-node@v4
           with:
              node-version-file: .nvmrc

         - name: Install dependencies
           run: npm ci

         - name: Run ESLint
           run: npm run lint

         - name: Run Prettier
           run: npm run format

         - name: Check for uncommitted changes
           run: |
              git diff --exit-code || (echo "Uncommitted changes after lint/format!" && exit 1)

         - name: Build site
           run: npm run build

         - name: Upload build artifact
           uses: actions/upload-artifact@v4
           with:
              name: dist
              path: ./dist

   deploy:
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      needs: check-and-build
      runs-on: ubuntu-latest
      steps:
         - name: Download build artifact
           uses: actions/download-artifact@v4
           with:
              name: dist
              path: ./dist

         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v4
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./dist
